### ISSUE TITLE
protobuf set to 3.20.0 in requirements.txt causes a failure 

### ISSUE THREAD

**Issue by causten** [ROCmSoftwarePlatform/AMDMIGraphX#1231]
Steps to reproduce 
1. Change the protobuf version in requirements.txt to 3.20.0
2. Run the ./tools/install_prereqs.sh
3. Kick off a build Clang_ASAN build

rm -rf build
mkdir build
cd build
CXX=/opt/rocm/llvm/bin/clang++ CXXFLAGS='-Werror' cmake -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=debug -DMIGRAPHX_ENABLE_PYTHON=Off -DMIGRAPHX_ENABLE_GPU=Off -DMIGRAPHX_ENABLE_CPU=On -DCMAKE_CXX_FLAGS_DEBUG='-g -O2 -fno-omit-frame-pointer -fsanitize=undefined,address -fno-sanitize-recover=undefined,address' ..
make -j$(nproc) generate all doc package check VERBOSE=1
 
5. See the error...

[2022-05-31T15:37:45.260Z] ld.lld: error: ../lib/libmigraphx_onnx.so.2.3: undefined reference to google::protobuf::internal::InternalMetadata::~InternalMetadata() [--no-allow-shlib-undefined]

**Comment by causten** [comment]
Note it works fine with protobuf 3.19.0

**Comment by kahmed10** [comment]
#4243 upgraded protobuf, no longer relevant
