### ISSUE TITLE
Cannot compile with half >= 2.0

### ISSUE THREAD

**Issue by dllu** [ROCmSoftwarePlatform/AMDMIGraphX#715]
When attempting to compile with `half 2.0`, I am getting some compilation errors:

```
build » make
[  0%] Built target onnx-proto
[  3%] Built target tf-proto
Scanning dependencies of target migraphx
[  3%] Building CXX object src/CMakeFiles/migraphx.dir/analyze_streams.cpp.o
[  3%] Building CXX object src/CMakeFiles/migraphx.dir/eliminate_common_subexpression.cpp.o
[  3%] Building CXX object src/CMakeFiles/migraphx.dir/auto_contiguous.cpp.o
[  3%] Building CXX object src/CMakeFiles/migraphx.dir/decompose.cpp.o
[  3%] Building CXX object src/CMakeFiles/migraphx.dir/propagate_constant.cpp.o
[  3%] Building CXX object src/CMakeFiles/migraphx.dir/eliminate_contiguous.cpp.o
[  3%] Building CXX object src/CMakeFiles/migraphx.dir/adjust_allocation.cpp.o
[  3%] Building CXX object src/CMakeFiles/migraphx.dir/eliminate_allocation.cpp.o
[  3%] Building CXX object src/CMakeFiles/migraphx.dir/dead_code_elimination.cpp.o
[  3%] Building CXX object src/CMakeFiles/migraphx.dir/eliminate_identity.cpp.o
[  6%] Building CXX object src/CMakeFiles/migraphx.dir/eliminate_concat.cpp.o
[  6%] Building CXX object src/CMakeFiles/migraphx.dir/eliminate_pad.cpp.o
In file included from /home/dllu/builds/AMDMIGraphX/src/eliminate_concat.cpp:2:
In file included from /home/dllu/builds/AMDMIGraphX/src/include/migraphx/eliminate_concat.hpp:6:
In file included from /home/dllu/builds/AMDMIGraphX/src/include/migraphx/concat_opt.hpp:11:
In file included from /home/dllu/builds/AMDMIGraphX/src/include/migraphx/operation.hpp:12:
In file included from /home/dllu/builds/AMDMIGraphX/src/include/migraphx/normalize_attributes.hpp:5:
In file included from /home/dllu/builds/AMDMIGraphX/src/include/migraphx/shape.hpp:11:
/home/dllu/builds/AMDMIGraphX/src/include/migraphx/half.hpp:27:35: error: no member named 'expr' in namespace 'half_float::detail'
struct deduce<half_float::detail::expr>
              ~~~~~~~~~~~~~~~~~~~~^
```
(and several more similar lines with the same error).

Apparently with half 2.0.0 the `expr` was removed.

By the way there is a `TODO: Fix the incorrect path` in `src/CmakeLists.txt` that is very annoying. It was not able to find the `half` that was installed on my system so I had to change the line above the TODO to be

```
find_path(HALF_INCLUDE_DIR half.hpp HINTS /usr/include/half)
```

**Comment by turneram** [comment]
Hi @dllu, we are currently working to add support for half 2.0 and newer, and will also be addressing the find_path issue.

In the meantime, a quick workaround would simply be to add the `expr` struct back to the `detail` namespace of the half header file. E.g.:


```
...
	namespace detail
	{ 
```
```
                // Temporary half-precision expression.
		/// This class represents a half-precision expression which just stores a single-precision value internally.
		struct expr
		{
			/// Conversion constructor.
			/// \param f single-precision value to convert
			explicit HALF_CONSTEXPR expr(float f) HALF_NOEXCEPT : value_(f) {}

			/// Conversion to single-precision.
			/// \return single precision value representing expression value
			HALF_CONSTEXPR operator float() const HALF_NOEXCEPT { return value_; }

		private:
			/// Internal expression value stored in single-precision.
			float value_;
		};
```
```
                /// Helper class for half casts.
		/// This class template has to be specialized for all valid cast arguments to define an appropriate static 
		/// `cast` member function and a corresponding `type` member denoting its return type.
		...
...
```

After editing `half.hpp`, rebuild MIGraphX starting from the `AMDMIGraphX` directory. E.g.:
```
rbuild build -d depend --cxx /opt/rocm/llvm/bin/clang++
cd build
CXX=/opt/rocm/llvm/bin/clang++ CXXFLAGS="-O3" cmake ..
make -j$(nproc)
sudo make install
make check -j$(nproc)
```
You should find all unit tests will be passing, but let us know if you are still encountering errors.

**Comment by mvermeulen** [comment]
Fixed.
